# Build
FROM golang:1.25-alpine AS build

COPY go.mod go.sum /
COPY internal/ /internal/
COPY api/ /api/

WORKDIR /api
RUN go build -o api

# Run
FROM alpine:latest
RUN apk add --no-cache tzdata
WORKDIR /
COPY --from=build /api/api .

EXPOSE 8000
ENTRYPOINT ["/api"]